[template]
src = "production.tmpl"
dest = "./config/default.json"
keys = [
	"/kafka/host_ip",
    "/kafka/topic",
    "/kafka/group_id",
    "/kafka/auto_commit",
    "/kafka/offset_reset",
    "/input_output/output_srs",
    "/input_output/output_format",
    "/input_output/folder_path",
    "/logger/level",
    "/logger/date_format",
    "/logger/filename",
    "/logger/format",
    "/task_fields"
]

