[template]
src = "production.tmpl"
dest = "./config/default.json"
keys = [
    "/configuration/exporter/worker/server/task/type",
    "/configuration/exporter/worker/server/job/type",
    "/configuration/exporter/worker/server/job/manager/url",
    "/configuration/exporter/worker/server/heartbeat/manager/url",
    "/configuration/exporter/worker/server/heartbeat/interval/ms",
    "/configuration/exporter/worker/fs/external_physical_path",
    "/configuration/exporter/worker/fs/internal_outputs_path",
    "/configuration/exporter/worker/logger/level",
    "/configuration/exporter/worker/logger/filename",
    "/configuration/exporter/worker/logger/backup/count",
    "/configuration/exporter/worker/logger/max/bytes",
    "/configuration/exporter/worker/max/attempts",
    "/configuration/exporter/worker/exportstorage/url",
    "/configuration/exporter/worker/gdal/multithread",
    "/configuration/exporter/worker/gdal/thread/count",
    "/configuration/exporter/worker/gdal/output_srs",
    "/configuration/exporter/worker/gdal/output_format",
    "/configuration/exporter/worker/s3/endpoint/url",
    "/configuration/exporter/worker/s3/access/key/id",
    "/configuration/exporter/worker/s3/secret/access/key",
    "/configuration/exporter/worker/s3/bucket",
    "/configuration/exporter/worker/s3/ssl/enabled",
    "/configuration/exporter/worker/storage/provider",
    "/configuration/exporter/worker/s3/download/proxy"
]
