[template]
src = "production.tmpl"
dest = "./config/default.json"
keys = [
	"/configuration/exporter/worker/kafka/host_ip",
    "/configuration/exporter/worker/kafka/topic",
    "/configuration/exporter/worker/kafka/group_id",
    "/configuration/exporter/worker/kafka/offset_reset",
    "/configuration/exporter/worker/kafka/poll_timeout_milliseconds",
    "/configuration/exporter/worker/kafka/poll_records",
    "/configuration/exporter/worker/fs/external_physical_path",
    "/configuration/exporter/worker/fs/internal_outputs_path",
    "/configuration/exporter/worker/logger/level",
    "/configuration/exporter/worker/logger/filename",
    "/configuration/exporter/worker/logger/backup/count",
    "/configuration/exporter/worker/logger/max/bytes",
    "/configuration/exporter/worker/max/attempts",
    "/configuration/exporter/worker/exportstorage/url",
    "/configuration/exporter/worker/gdal/multithread",
    "/configuration/exporter/worker/gdal/thread/count",
    "/configuration/exporter/worker/gdal/output_srs",
    "/configuration/exporter/worker/gdal/output_format",
    "/configuration/exporter/worker/s3/endpoint/url",
    "/configuration/exporter/worker/s3/access/key/id",
    "/configuration/exporter/worker/s3/secret/access/key",
    "/configuration/exporter/worker/s3/bucket",
    "/configuration/exporter/worker/storage/provider",
    "/configuration/exporter/worker/s3/download/expired/time"
]
