[template]
src = "production.tmpl"
dest = "./config/default.json"
keys = [
	"/configuration/exporter/worker/kafka/host_ip",
    "/configuration/exporter/worker/kafka/topic",
    "/configuration/exporter/worker/kafka/group_id",
    "/configuration/exporter/worker/kafka/offset_reset",
    "/configuration/exporter/worker/kafka/poll_timeout_milliseconds",
    "/configuration/exporter/worker/kafka/poll_records",
    "/configuration/exporter/worker/input_output/output_srs",
    "/configuration/exporter/worker/input_output/output_format",
    "/configuration/exporter/worker/input_output/external_physical_path",
    "/configuration/exporter/worker/input_output/internal_outputs_path",
    "/configuration/exporter/worker/logger/level",
    "/configuration/exporter/worker/logger/filename",
    "/configuration/exporter/worker/logger/backup/count",
    "/configuration/exporter/worker/logger/max/bytes",
    "/configuration/exporter/worker/max/attempts",
    "/configuration/exporter/worker/exportstorage/url",
    "/configuration/exporter/worker/gdal/multithread",
    "/configuration/exporter/worker/gdal/thread/count"
]
